### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by selwynpolit** [selwynpolit/d9book#104]
@maks-oleksyuk Could you take a peek?  I'm seeing build errors when I try to push changes.

**Comment by maks-oleksyuk** [comment]
@selwynpolit It seems that the ci images used by github have updated the major version of pnpm, which led to errors, I updated the dependencies, but it may happen again when a new version is released, it seems that this check can be disabled, but that's a little later.

**Comment by selwynpolit** [comment]
Thanks @maks-oleksyuk It is working great again!

**Comment by selwynpolit** [comment]
@maks-oleksyuk I just tried another merge and github is complaining about pnpm issues:

```
Run pnpm i --frozen-lockfile --color=always
  pnpm i --frozen-lockfile --color=always
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    PNPM_FLAGS: --frozen-lockfile --color=always
 ERR_PNPM_BAD_PM_VERSION  This project is configured to use v9.0.[4](https://github.com/selwynpolit/d9book/actions/runs/8804494573/job/24165021797#step:5:4) of pnpm. Your current pnpm is v9.0.[5](https://github.com/selwynpolit/d9book/actions/runs/8804494573/job/24165021797#step:5:5)

If you want to bypass this version check, you can set the "package-manager-strict" configuration to "false" or set the "COREPACK_ENABLE_STRICT" environment variable to "0"
Error: Process completed with exit code 1.
```

Could you please take a look?

**Comment by selwynpolit** [comment]
I see in the package.json file where the pnpm is set to 9.0.4
I guess I could try change that to 9.0.5. hmmm

**Comment by maks-oleksyuk** [comment]
This is a new feature of pnpm that allows you to monitor the correspondence between the versions installed and declared in the project, but ci always installs the latest version, which causes an error

**Comment by maks-oleksyuk** [comment]
it seems the env setting for ci-cd changes the error to a warning, see the newly created PR, I deliberately didn't increase the pnpm version in packaje.json to test how the action would work
