### ISSUE TITLE
I need some help with styling

### ISSUE THREAD

**Issue by selwynpolit** [selwynpolit/d9book#15]
Any front end dev want to help with some styling of the book?  Please let me know.  It also needs some mobile friendly theming help (if that is even possible for this kind of site).

**Comment by selwynpolit** [comment]
TOC have weird spacing e.g. https://selwynpolit.github.io/d9book/book/forms.html

**Comment by selwynpolit** [comment]
Also width is weird on https://selwynpolit.github.io/d9book/book/forms.html

**Comment by selwynpolit** [comment]
h2 and h3 sizes seem too similar. Maybe there could be some visual cue?  There is a horizontal line but it just seems like they run into each other... e.g.  https://selwynpolit.github.io/d9book/book/forms.html

**Comment by alesrebec** [comment]
I would increase all fonts to 150%.

Sceenshot how it looks now:
![Screenshot from 2023-03-01 12-05-36](https://user-images.githubusercontent.com/426177/222122828-383082a7-daeb-41ec-8982-6e9bc23206b2.png)

With 150% font thoughout the whole site:
![Screenshot from 2023-03-01 12-05-49](https://user-images.githubusercontent.com/426177/222122826-09a93d15-b592-441f-b4b6-4d69825d89f9.png)

![Screenshot from 2023-03-01 12-05-58](https://user-images.githubusercontent.com/426177/222122820-f67cae58-1c37-47aa-ba0c-d1a8ddde800d.png)


I would also consider width in div.shell which is now set to 670px and really looks too narrow on any bigger screen.
Just too bad not using more width for the text an code.

Quick test (screenshot) with increased width of div.shell:
![Screenshot from 2023-03-01 12-11-17](https://user-images.githubusercontent.com/426177/222123252-e5c1166f-356c-4597-b4eb-a71d126b79ed.png)

**Comment by selwynpolit** [comment]
Thanks for this @alesrebec I will give these as try ASAP

**Comment by maks-oleksyuk** [comment]
Hello
looking at the current theme, you can notice several unpleasant moments, such as block width limitations and mismatching the block width with the text. This reduces the attractiveness of the site for me.

**Proposed resolution:**
Perhaps you should consider the [just-the-docs](https://github.com/just-the-docs/just-the-docs) theme for the site design.
I noticed that this theme was once [used](https://github.com/selwynpolit/d9book/commit/c8ff18e4971da8e1f77e9ab13529b4541909b769#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883R1) in the settings.
This theme has some pretty great customization and [ui components](https://just-the-docs.github.io/just-the-docs/docs/ui-components).

**Comment by selwynpolit** [comment]
@maks-oleksyuk Thanks for the thoughts. I also hate how unattractive and unprofessional the look of the site is.  I did fiddle with just-the-docs theme but I think I had some problems with it.  It was a while ago. I really did like many aspects of it.  

 Unfortunately I am really weak with front end stuff so I need some help.  If you are open to a zoom call and taking a look with me, that would be awesome.

**Comment by selwynpolit** [comment]
@alesrebec I implemented some of the changes you suggested (to the best of my knowledge.) Let me know what you think and thanks again.

**Comment by maks-oleksyuk** [comment]
@selwynpolit thanks for the answer

I made a quick setup to use the just-the-docs theme to demonstrate a possible look of the site.

![image](https://user-images.githubusercontent.com/90793591/230883279-af35d630-a509-420e-a690-2a09b410e34c.png)
Here's what the desktop version looks like 

![image](https://user-images.githubusercontent.com/90793591/230883541-6f59595b-e894-44a0-9089-31b213fd0bc5.png)
This theme also looks good on mobile devices.

Don't be surprised by the dark theme, I've specified it in the settings.

Also, this theme has many other settings for colors, search, breadcrumbs, and others that need to be customized.
But changing to this theme would require reworking all the `.md` files to add the necessary information for the theme.

I am also not very strong in this area, but I will be happy to help in any way I can if possible.

**Comment by alesrebec** [comment]
> 

It looks much better now already.
Though I agree having Just the Docs and leveraging the side menu would be perfect.

**Comment by maks-oleksyuk** [comment]
It's great to know that you support these changes.

I have partially worked on redesigning the site with a new theme. I'm still looking for better solutions or improvements, so any criticism or comments will be helpful.

I have created a copy of the site - https://maks-oleksyuk.github.io/d9book/bq

Here is a small summary of the changes:
- the main theme has been changed (the necessary settings have been added to the `_config.yml` file)
- static content of the file is replaced by dynamic content
- updated code blocks (removed `<?php`, some places are optimized for coding standards, added type annotation for PHP 8)
- minor changes in the text
- added some footnotes (warning, see also)
- copyright is placed in the footer of the site
- added 404 page
- added links to the author's repository and Twitter)
- added buttons with links to the top and to editing

ось декілька фото для порівняння(масштаб 75% до 50%)
![image](https://user-images.githubusercontent.com/90793591/231290575-92c6f928-58c2-4bf9-bfb1-cea8e09b936b.png)
![image](https://user-images.githubusercontent.com/90793591/231290702-b7a8c8ef-6ecd-478a-b570-80e74e684e46.png)
![image](https://user-images.githubusercontent.com/90793591/231290818-025069ed-ec42-4761-8b80-2176cd3e4008.png)

I also have a few questions/comments
- the theme supports configuration for [Analytics](https://just-the-docs.github.io/just-the-docs/docs/configuration/#google-analytics)
- whether [comments](https://github.com/maks-oleksyuk/d9book/blob/gh-pages/book/bq.md?plain=1#L607) on the article are needed
- fixing some [links](https://github.com/maks-oleksyuk/d9book/blob/gh-pages/book/bq.md?plain=1#L47)

Thank you

**Comment by selwynpolit** [comment]
Yeah, that site looks really nice.  How much change is required in the actual chapters?

**Comment by selwynpolit** [comment]
and that side menu is great.

**Comment by maks-oleksyuk** [comment]
> Yeah, that site looks really nice. How much change is required in the actual chapters?

For each article, you need to add information about the template to the beginning of the page, I have already added this data in the pull request. Maybe only some small details are missing (links, typos, etc.).
