### ISSUE TITLE
Add example for form api entity autocomplete using a view to search.

### ISSUE THREAD

**Issue by nlighteneddesign** [selwynpolit/d9book#25]
I was looking for how to use a view for an entity autocomplete search and didn't see any examples.
Here is how it works:
$form['user'] = [
  '#type' => 'entity_autocomplete',
  '#target_type' => 'user',
  '#selection_handler' => 'views',
  '#selection_settings' => [
    'view' => [
      'view_name' => 'users_view',
      'display_name' => 'users',
      'arguments' => []
    ], 
    'match_operator' => 'CONTAINS'
  ],
];
I used this reference and confirmed it: https://drupal.stackexchange.com/questions/308870/entity-autocomplete-form-api-field-with-viewsselection-handler

I'm not sure of your contribution guidelines or styleguide but I was looking in this section:
https://selwynpolit.github.io/d9book/book/forms.html

**Comment by selwynpolit** [comment]
Thanks Nic, 
I added your example.  I don't really have contribution guidelines or a styleguide - Just add what you think others can use (or that you want to remember) in a way that is as clear as possible.  You can easily create a PR by directly editing the file you want to [here](https://github.com/selwynpolit/d9book/tree/gh-pages/book). There is a very simple editor which automatically forks the repo and lets you type your changes directly in your browser in [markdown format](https://github.github.com/gfm/).

**Comment by selwynpolit** [comment]
You inspired me to do a significant rearrange of that whole chapter btw.  Keep em coming!
