### ISSUE TITLE
Refresh the main page of the repository

### ISSUE THREAD

**Issue by maks-oleksyuk** [selwynpolit/d9book#41]
Suggestion to update the settings like in the screenshot
![image](https://user-images.githubusercontent.com/90793591/235260533-a1802999-8ef3-42ab-ad62-a17b21f8f428.png)

The result will look like this.
![image](https://user-images.githubusercontent.com/90793591/235260978-74948154-0a67-4e8c-a80e-bb11925d60d2.png)

This will provide the following benefits:
- Quick access to the site with a link
- Keywords and description for better search and promotion on GitHub
- Hiding unnecessary information

**Comment by selwynpolit** [comment]
Done.  Thanks!
