### ISSUE TITLE
Page counter is broken

### ISSUE THREAD

**Issue by selwynpolit** [selwynpolit/d9book#45]
Each page had a page counter which let folks know how many times it had been read.  Unfortunately this broke.  Anyone have a good alternative?

**Comment by arysom** [comment]
I saw there are alternative services in description of that service, and digging trough them lead me to https://plantree.github.io/project-docs/visitor-badge/introduction.html .

**Comment by maks-oleksyuk** [comment]
A great alternative from @arysom
I created a test badge that works on my fork.

I did not create a badge for the main site, as this requires a secret key to be created by @selwynpolit

Here is the badge code and the badge itself

```md
![image](https://api.visitor.plantree.me/visitor-badge/pv?label=visitors&color=informational&namespace=maks-oleksyuk.github.io&key=d9book)
```

![image](https://api.visitor.plantree.me/visitor-badge/pv?label=visitors&color=informational&namespace=maks-oleksyuk.github.io&key=d9book)

We can probably change the theme or color if needed

**Comment by selwynpolit** [comment]
Thanks @maks-oleksyuk and @arysom - I implemented this on the [index ](https://selwynpolit.github.io/d9book/)and [actions ](https://selwynpolit.github.io/d9book/actions)page.  Let me know what you think.

**Comment by maks-oleksyuk** [comment]
I like the following option more:
![views](https://api.visitor.plantree.me/visitor-badge/pv?label=views&color=informational&namespace=d9book&key=index.md)
- It's a different style, it's not the main information and I don't think it needs to stand out as much as in `?style=for-the-badge`
- A more general text was used for the text on the badge (_"views"_). I think it is more appropriate and is used on many sites

**Comment by arysom** [comment]
I'm not good at designing things but I agree with Maks' opinion. Of course the final decision is up to you Selvyn. The book won't loose anything even without page's view counter :)

**Comment by maks-oleksyuk** [comment]
I created a request (#62) to change all badges to new ones
