### ISSUE TITLE
Add example for Hook Form alter in OOPS way

### ISSUE THREAD

**Issue by bhanu951** [selwynpolit/d9book#53]
Here is a reference for Hook Form alter in OOPS way [content_moderation.module](https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/content_moderation/content_moderation.module#L164)
[EntityTypeInfo](https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/content_moderation/src/EntityTypeInfo.php#L334)

Another example [organise-your-hooks-code-classes-object-oriented-way](https://www.berramou.com/blog/drupal-8-how-organise-your-hooks-code-classes-object-oriented-way)

**Comment by selwynpolit** [comment]
Thanks @bhanu951 - I added this to the hooks chapter at https://selwynpolit.github.io/d9book/hooks#organizing-your-hooks-code-the-oop-way 
Please feel free to click the edit button at the bottom of the page and add any additional thoughts.
