### ISSUE TITLE
Add a LICENSE file?

### ISSUE THREAD

**Issue by gitressa** [selwynpolit/d9book#61]
The "Debian Bullseye from Discovery to Mastery" is a great open source handbook:

- https://debian-handbook.info/
- https://gitlab.com/debian-org/book

It uses the GNU General Public License as far as I can tell:

- https://gitlab.com/debian-org/book/-/blob/main/LICENSE
- https://www.gnu.org/licenses/gpl-3.0.html

Perhaps a license could also be added to this project?

**Comment by maks-oleksyuk** [comment]
I believe that we can close this problem.

After a recent upgrade from @selwynpolit to D10, the repository contains a GPL-3.0 license file.

**Comment by gitressa** [comment]
You're right @maks-oleksyuk, thanks! https://github.com/selwynpolit/d9book/blob/main/LICENSE.md
