### ISSUE TITLE
We need a page on how to contribute

### ISSUE THREAD

**Issue by selwynpolit** [selwynpolit/d9book#98]
Turns out it isn't quite as easy to contribute to this project as I had hoped.  From editing directly on github.com to setting the target branch on the pull request to gh-pages, or downloading a copy of the site, editing, committing, pushing and creating a pull request, I suspect it is a little challenging for folks...

It would be great to add a page.  Perhaps someone could do a screencast or instructions or both.

**Comment by maks-oleksyuk** [comment]
I think we can start with this
https://github.com/firstcontributions/first-contributions

**Comment by selwynpolit** [comment]
Thanks @maks-oleksyuk - I added https://selwynpolit.github.io/d9book/contributing so we have a start now.  Maybe someone will contribute further.

**Comment by maks-oleksyuk** [comment]
I think it would be nice to have a default gh-pages branch, since this is the branch where the book is stored, and Github will suggest creating PRs in this branch by default

**Comment by selwynpolit** [comment]
Yeah, I started looking at that.  Do you mean to set the default branch to gh-pages?  I didn't see an option to do that under the branches listing.  Suggestions?

**Comment by maks-oleksyuk** [comment]
@selwynpolit See `Settings` -> `General` -> `Default branch` in repo

**Comment by selwynpolit** [comment]
Got it.  Thanks @maks-oleksyuk
